"""change vector dimension

Revision ID: 5f18b13a7736
Revises: 9fec206fe3d4
Create Date: 2026-09-26 18:04:47.572800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '5f18b13a7736'
down_revision: Union[str, Sequence[str], None] = '9fec206fe3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedding',
               existing_type=Vector(384),
               type_=Vector(1536),
               existing_nullable=True)
    # ### end Alembic commands ###
